create table public.comment_keyword_reply (
  rule_id uuid not null default extensions.uuid_generate_v4 (),
  automation_id uuid not null,
  platform_user_id text null,
  provider_id text null,
  post_selection_type text not null default 'ALL'::text,
  specific_post_ids text[] null,
  date_range text null default '1d'::text,
  trigger_type text not null,
  keywords text null default 'NO KEYWORD'::text,
  match_type text null default 'CONTAINS'::text,
  ai_context_rules text null default 'NO RULES given'::text,
  reply_type text null,
  custom_reply text null,
  system_prompt text null default 'You are a helpful and engaging social media assistant.'::text,
  comment_reply_template_type text null default 'PLAIN_TEXT'::text,
  max_replies_per_post integer null,
  reply_count_condition text null default 'LESS_THAN'::text,
  reply_count_value integer null default 1,
  model_provider text null default 'OPENAI'::text,
  model_name text not null default 'gpt-4o'::text,
  temperature numeric(2, 1) null default 0.7,
  is_rag_enabled boolean null default false,
  confidence_threshold numeric(3, 2) null default 0.75,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint comment_keyword_reply_pkey primary key (rule_id),
  constraint comment_keyword_reply_automation_id_key unique (automation_id),
  constraint comment_keyword_reply_automation_id_fkey foreign KEY (automation_id) references automations (automation_id) on delete CASCADE
) TABLESPACE pg_default;