create table public.private_message (
  rule_id uuid not null default extensions.uuid_generate_v4 (),
  automation_id uuid not null,
  platform_user_id text null,
  provider_id text null,
  post_selection_type text not null default 'ALL'::text,
  specific_post_ids text[] null,
  date_range text null default '1d'::text,
  trigger_type text not null,
  keywords text null default 'NO KEYWORD'::text,
  match_type text null default 'CONTAINS'::text,
  ai_context_rules text null default 'NO RULES given'::text,
  system_prompt text null default 'You are a helpful and engaging social media assistant'::text,
  reply_template_type text null default ''::text,
  reply_template_content text not null,
  model_provider text null default 'OPENAI'::text,
  model_name text not null default 'gpt-4o'::text,
  temperature numeric(2, 1) null default 0.7,
  is_rag_enabled boolean null default false,
  confidence_threshold numeric(3, 2) null default 0.75,
  model_usage text not null default 'PLATFORM_DEFAULT'::text,
  schedule_type text not null default 'CONTINUOUS'::text,
  max_actions integer null,
  time_period_seconds integer not null default 60,
  user_cooldown_seconds integer not null default 300,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint private_message_pkey primary key (rule_id),
  constraint private_message_automation_id_key unique (automation_id),
  constraint private_message_automation_id_fkey foreign KEY (automation_id) references automations (automation_id) on delete CASCADE
) TABLESPACE pg_default;